export const
    MAX_MESSAGE_EMBEDS = 10,
    MAX_EMBED_TITLE = 256,
    MAX_EMBED_DESCRIPTION = 2048,
    MAX_EMBED_FIELDS = 25,
    MAX_FIELD_NAME = 256,
    MAX_FIELD_VALUE = 1024,
    MAX_EMBED_FOOTER = 2048,
    MAX_EMBED_AUTHOR = 256,
    MAX_EMBED_SUM = 6000,
    MAX_ACTION_ROWS = 5,
    MAX_ROW_COMPONENTS = 5,
    MAX_BUTTON_LABEL = 80;
