export const
    MAX_CHANNEL_NAME = 100,
    MAX_THREAD_NAME = MAX_CHANNEL_NAME,
    MAX_MESSAGE_EMBEDS = 10,
    MAX_EMBED_TITLE = 256,
    MAX_EMBED_DESCRIPTION = 4096,
    MAX_EMBED_FIELDS = 25,
    MAX_FIELD_NAME = 256,
    MAX_FIELD_VALUE = 1024,
    MAX_ACTION_ROWS = 5,
    MAX_ROW_COMPONENTS = 5;
